coderefinery/reproducible-research

_episodes/01-why-reproducible-research.md
_episodes/02-what-is-reproducible-research.md
_episodes/03-containers-for-reproducible-research.md

just a small contribution with language and style fixes

small languages edits and such

---

guide.md

first draft of instructor guide, should be expanded as more instructor experience is obtained

Thor instructor guide

---

_episodes/03-workflow-management.md

shortened the make part since we focus on snakemake. Small edits here and there

reworking workflow episode

---

_episodes/04-containers.md

mostly adding clarifications here and there

revising the container episode

---

_episodes/03-workflow-management.md

it can be good to have an analogous exercise for make as for snakemake, in case someone prefers make
or has snakemake installation problems

Remove old make exercise, and add a new which mirrors the snakemake one

---

_episodes/02-organizing-projects.md
_episodes/03-workflow-management.md

- One slide on FAIR data (split out to new episode?)
- minor bugfixes
---
In the end there wasn't that much to do right now.  This lesson has basics of data organization and sharing built in, and if we want to do more we'd make a new episode and a clever example... and a way to keep it interesting.

Minor changes for Espoo, plus FAIR data description

---

_config.yml

Plus cleanup in `_config.yml`.

instead of showing start times, show episode durations

---

_config.yml
_episodes/03-sharing.md
_episodes/04-dependencies.md
_episodes/06-workflow-management.md
_episodes/07-docker.md

fixing small issues

---

_episodes/02-organizing-projects.md

adding links to rttools, jupyter, mybinder. Fixes #44 and fixes #78

split into separate section for reprodible publications

---

_episodes/03-sharing.md

also move list to end of episode since it's a reference

add list to nordic data services and platforms

---

guide.md

restructure and add sections "why we teach the lesson" and "intended learning outcomes"

update instructor guide 

---

_episodes/06-workflow-management.md

formatting changes and introduction of new optional snakemake+conda exercise

update snakemake episode

---

_episodes/06-workflow-management.md

follow-up to #114 , i forgot to move the exercises...

mv exercises to after theory sections

---

_episodes/02-organizing-projects.md
_episodes/03-dependencies.md
_episodes/05-workflow-management.md

mixed updates

---

_episodes/02-organizing-projects.md

Mentionhackmd

---

_episodes/06-sharing.md

Mention fair-software.eu

---

_episodes/03-dependencies.md

Mention devtools

---

_episodes/04-workflow-management.md

Mention snakemake clean output command

---

guide.md

The instructor guide has been updated in line with the discussion in #132.
Closes #132

Updated instructor guide on the snakemake episode

---

_episodes/05-environments.md

Implemented text on docker analogies in line with discussion in #68.
Closes #68

Added Docker analogy

---

_episodes/03-dependencies.md

Revised the conda environment exercise following the discussion on Zulip.

Revised conda environment exercise

---

_episodes/04-workflow-management.md

Augmented to describe how the environment needed for the snakemake exercise can be set up on either local computer or on mybinder.

Extended exercise preparations

---

content/dependencies.md
content/docker.md
content/exercises.md
content/guide.md
content/index.rst
content/motivation.md
content/organizing-projects.md
content/sharing.md
content/workflow-management.md

first batch of updates for march 2022 workshop

closing issues and adding list of exercises

---

content/dependencies.md
content/docker.md
content/environments.md
content/organizing-projects.md
content/workflow-management.md

most significant: new optional Docker exercise using play with docker, so that interested learners have something to do if time allows

update docker and some smaller improvements

---

content/index.rst
content/motivation.md
content/organizing-projects.md

Small updates to various text

---

content/dependencies.md
content/docker.md

- Also a few `shell` -> `console`

Indent various code blocks

---

content/index.rst

- For those that look at this lesson, it will connect better to them
before reading the second paragraph.  This probably isn't discussed
in the course itself, this is a copy of "motivation".
- Review: automerge

content/index: Researcher-focused intro paragraph on the front page

---

content/organizing-projects.md

- Add an intro, add some links
- Review: automerge

content/organizing-projects: Minor updates

---

content/workflow-management.md

- No major changes, but try to improve clarity throughout the page.
- No changes in exercises or material.
- Review: automerge

content/workflow-management: Misc updates

---

content/environments.md

- No real content changes
- Review: automerge

content/environments: misc updates to the page

---

content/guide.md

- Maybe these kind of reports are useful for the future?
- Review: check if anything else should be added and if this is a good
idea.

content/guide: Add "field report" from 2022 september

---

content/organizing-projects.md

Simplified text and changed exercise to discussion

Organising projects -episode

---

content/dependencies.md

The python version is missing in the `environment.yml`, even though it is normally stored there.

Add python version; fix #232

---

content/environments.md

content/environments: mobile kitchens are factory-built food trucks

---

content/guide.md

Resolves #236 
Note that the material does not yet reflect the order of things mentioned in schedule.
@eglerean please also read #236 first  for explanation :)

Add new planned schedule

---

content/dependencies.md
content/environments.md

mark optional exercises for sep 23 workshop

---

content/workflow-management.md

- exercise to demo
- bring bash script back, but to word count repo
- simplify snakefile, move conda thingy to "why snakemake"
- reorder

Small updates to snakemake lesson 

---

CITATION.cff
content/conf.py

draft written. Please check and adapt if needed

Add CITATION.cff

---

content/dependencies.md
content/environments.md
content/intro.md
content/motivation.md
content/organizing-projects.md
content/where-to-go.md
content/workflow-management.md

Turned reproducible manuscript section into an excursion, as it does not not quite fit into the general section of organizing your projects and made the text more clear (hopefully?).
Some lessons were missing the objective box
Some "solutions" were missing for being self-learning ready. 
Some consistency updates and other small fixes.  
Review: Please read carefully if ok :)

Smallish edits to lessons

---

CITATION.cff

add "yonglei wang" as one author in the CITATION.cff

update CITATION.cff file

---

CITATION.cff

@samumantha I fixed it in the Zenodo record draft.

fix given name
